### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [rubendv/sodiumpp#22]
Hi @rubendv, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by rubendv** [comment]
I don’t really have the time anymore unfortunately. It would probably be for the best if this library was removed from the official binding list.

**Comment by samuel-lucas6** [comment]
Thanks for getting back to me.

**Comment by samuel-lucas6** [comment]
I'm going to close this to help keep track of who hasn't replied yet. I recommend archiving the repository if you want to make it clear that it's no longer maintained.
